### PR TITLE
Update package description

### PR DESCRIPTION
**Pull request by pmeinhardt**
SSHKit will be/is more than just a wrapper around the underlying Erlang
ssh libraries, supporting SCP and ultimately implementing a DSL for
specifying how to run tasks on remote machines.

### CODE REVIEW

**Comment by xhr15** [comment]
I think we should decide for a state that sshkit will be in when we "release" it. We should describe this state as "present', so we can have a clearer language. 

Future stages should then IMHO go into the roadmap on the repo, so the reader knows "what she gets when she installs it right now" when she reads the description, not more not less

**Comment by xhr15** [comment]
👍 for changing the description

**Comment by xhr15** [comment]
maybe add that we are using erlangs ssh: "... on top of Erlangs ssh app"?

**Comment by pmeinhardt** [comment]
Good suggestion! Updated the description.

**Pull request merged**
