### PR TITLE
Functional testing

### PR DESCRIPTION
**Pull request by tessi**
There's a rough outline of how to create functional tests on the `tests` branch.

Basic thinking here was to start a couple of docker containers running `sshd` to check against a proper SSH server on a real operating system.

There's some code in place to build a slim Alpine Linux image whenever starting the test suite and running containers off of it for each test.

See `test_helper.exs` and `test/support/docker.ex`.

Then for tests, we imagine using tags could be nice"

```elixir
@machines [users: [], …]
test "runs command as a specific user", %{machines: machines} do
  # machines contains the machine config (ports, usernames, password…)
  res = 
    SSHKit.context(hosts)
    |> SSHKit.user("paulo")
    |> SSHKit.run("whoami")

  # Check history for expected command, sth. like:
  history = Docker.exec!(container, "history") |> String.split("\n")

  # Assert it's been run with the correct context (pwd, …)
  assert List.last(history) == "sudo -u paulo -- whoami"

  # For testing SCP we probably need to assert file checksums, timestamps, file mode…
end
```

### CODE REVIEW

**Comment by pmeinhardt** [comment]
Just had a few ideas on how to conveniently set up the functional test cases (see 29eb200). Looks pretty neat I think, but happy about any feedback.

You just do:

```elixir
defmodule SSHTestUsingDocker do
  use SSHKit.FunctionalCase

  @tag boot: 3
  test "boots hosts running SSH", %{hosts: hosts} do
    assert length(hosts) == 3

    # host configurations contain details on
    # container id, SSH port number, etc.
    %{port: port} = List.first(hosts)
  end
end
```

TODOs

- [ ] set up a non-root user on each host by default (store name in `host` config)
- [ ] generate a (short!) SSH key for that user (store in config)
- [ ] write helper functions to inspect history, file-system for writing assertions (via `Docker.exec!`)

I think @paulodiniz, you had already started working on a couple of assertions/helpers?

Cheers

**Comment by pmeinhardt** [comment]
Feedback very much welcome! To get this running on your machine, you'll need to have `docker` installed (also `docker-machine` if you're on OS X/Windows).

You can run just the `:functional` tests, using:

```shell
mix test --only functional
```

or, if you want to run everything but the `:functional` tests:

```shell
mix test --exclude functional
```

If you'd like to see, which test cases are actually run, just append `--trace`.

**Comment by svoynow** [comment]
+1 for this. We've been moving in a similar direction for functional tests for the application we're building using `sshkit`

**Comment by tessi** [comment]
I've added some more functional tests now (and reviewed the existing work).

IMO this is good to merge, some reviews would be nice, though :)

**Comment by tessi** [comment]
PS: i skipped some tests where I think I experienced bugs. I'll file issues to investigate/fix them.

**Pull request merged**
